// Code generated by AMOS Go types generator v1; DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
)

type OptionalNullable[T any] struct {
	Value   T
	Present bool
	Null    bool
}

func (field *OptionalNullable[T]) UnmarshalJSON(data []byte) error {
	field.Present = true
	if bytes.Equal(bytes.TrimSpace(data), []byte("null")) {
		field.Null = true
		var zero T
		field.Value = zero
		return nil
	}
	field.Null = false
	return json.Unmarshal(data, &field.Value)
}
func (field OptionalNullable[T]) MarshalJSON() ([]byte, error) {
	if field.Null {
		return []byte("null"), nil
	}
	return json.Marshal(field.Value)
}

type jsonMember struct {
	name  string
	value []byte
}

func marshalObject(members []jsonMember) ([]byte, error) {
	var output bytes.Buffer
	output.WriteByte('{')
	for i, member := range members {
		if i > 0 {
			output.WriteByte(',')
		}
		name, err := json.Marshal(member.name)
		if err != nil {
			return nil, err
		}
		output.Write(name)
		output.WriteByte(':')
		output.Write(member.value)
	}
	output.WriteByte('}')
	return output.Bytes(), nil
}

type ErrorResponse struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	RequestID string `json:"requestId"`
}

type OperationPolicy struct {
	OperationID  string
	Permissions  []string
	Entitlements []string
	Assurance    string
	SideEffect   string
	Idempotency  string
	MCP          string
}
type OperationMetadata struct {
	Method string
	Path   string
	Policy OperationPolicy
}
type ModelCreateTodo struct {
	Title       ModelCreateTodoTitle       `json:"title"`
	WorkspaceId ModelCreateTodoWorkspaceId `json:"workspaceId"`
}

func (value ModelCreateTodo) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 2)
	encoded0, err := json.Marshal(value.Title)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"title", encoded0})
	encoded1, err := json.Marshal(value.WorkspaceId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"workspaceId", encoded1})
	return marshalObject(members)
}
func (value *ModelCreateTodo) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelCreateTodo
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["title"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["title"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["workspaceId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["workspaceId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelCreateTodo(decoded)
	return nil
}

type ModelCreateTodoTitle string

type ModelCreateTodoWorkspaceId string

type ModelDeleteTodo struct {
	Revision    ModelDeleteTodoRevision    `json:"revision"`
	TodoId      ModelDeleteTodoTodoId      `json:"todoId"`
	WorkspaceId ModelDeleteTodoWorkspaceId `json:"workspaceId"`
}

func (value ModelDeleteTodo) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 3)
	encoded0, err := json.Marshal(value.Revision)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"revision", encoded0})
	encoded1, err := json.Marshal(value.TodoId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"todoId", encoded1})
	encoded2, err := json.Marshal(value.WorkspaceId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"workspaceId", encoded2})
	return marshalObject(members)
}
func (value *ModelDeleteTodo) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelDeleteTodo
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["revision"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["revision"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["todoId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["todoId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["workspaceId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["workspaceId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelDeleteTodo(decoded)
	return nil
}

type ModelDeleteTodoRevision int64

type ModelDeleteTodoTodoId string

type ModelDeleteTodoWorkspaceId string

type ModelListTodos struct {
	WorkspaceId ModelListTodosWorkspaceId `json:"workspaceId"`
}

func (value ModelListTodos) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 1)
	encoded0, err := json.Marshal(value.WorkspaceId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"workspaceId", encoded0})
	return marshalObject(members)
}
func (value *ModelListTodos) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelListTodos
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["workspaceId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["workspaceId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelListTodos(decoded)
	return nil
}

type ModelListTodosWorkspaceId string

type ModelTodo struct {
	Completed   ModelTodoCompleted   `json:"completed"`
	Id          ModelTodoId          `json:"id"`
	Revision    ModelTodoRevision    `json:"revision"`
	Title       ModelTodoTitle       `json:"title"`
	WorkspaceId ModelTodoWorkspaceId `json:"workspaceId"`
}

func (value ModelTodo) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 5)
	encoded0, err := json.Marshal(value.Completed)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"completed", encoded0})
	encoded1, err := json.Marshal(value.Id)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"id", encoded1})
	encoded2, err := json.Marshal(value.Revision)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"revision", encoded2})
	encoded3, err := json.Marshal(value.Title)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"title", encoded3})
	encoded4, err := json.Marshal(value.WorkspaceId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"workspaceId", encoded4})
	return marshalObject(members)
}
func (value *ModelTodo) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelTodo
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["completed"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["completed"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["id"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["id"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["revision"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["revision"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["title"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["title"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["workspaceId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["workspaceId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelTodo(decoded)
	return nil
}

type ModelTodoCompleted bool

type ModelTodoId string

type ModelTodoList struct {
	Todos ModelTodoListTodos `json:"todos"`
}

func (value ModelTodoList) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 1)
	encoded0, err := json.Marshal(value.Todos)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"todos", encoded0})
	return marshalObject(members)
}
func (value *ModelTodoList) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelTodoList
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["todos"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["todos"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelTodoList(decoded)
	return nil
}

type ModelTodoListTodos []ModelTodo

type ModelTodoRevision int64

type ModelTodoTitle string

type ModelTodoWorkspaceId string

type ModelUpdateTodo struct {
	Completed   ModelUpdateTodoCompleted   `json:"completed"`
	Revision    ModelUpdateTodoRevision    `json:"revision"`
	Title       ModelUpdateTodoTitle       `json:"title"`
	TodoId      ModelUpdateTodoTodoId      `json:"todoId"`
	WorkspaceId ModelUpdateTodoWorkspaceId `json:"workspaceId"`
}

func (value ModelUpdateTodo) MarshalJSON() ([]byte, error) {
	members := make([]jsonMember, 0, 5)
	encoded0, err := json.Marshal(value.Completed)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"completed", encoded0})
	encoded1, err := json.Marshal(value.Revision)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"revision", encoded1})
	encoded2, err := json.Marshal(value.Title)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"title", encoded2})
	encoded3, err := json.Marshal(value.TodoId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"todoId", encoded3})
	encoded4, err := json.Marshal(value.WorkspaceId)
	if err != nil {
		return nil, err
	}
	members = append(members, jsonMember{"workspaceId", encoded4})
	return marshalObject(members)
}
func (value *ModelUpdateTodo) UnmarshalJSON(data []byte) error {
	if len(bytes.TrimSpace(data)) == 0 || bytes.TrimSpace(data)[0] != '{' {
		return errors.New("expected JSON object")
	}
	type plain ModelUpdateTodo
	var decoded plain
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&decoded); err != nil {
		return err
	}
	var trailing struct{}
	if err := decoder.Decode(&trailing); err != io.EOF {
		return errors.New("trailing JSON data")
	}
	var members map[string]json.RawMessage
	if err := json.Unmarshal(data, &members); err != nil {
		return err
	}
	if _, ok := members["completed"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["completed"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["revision"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["revision"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["title"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["title"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["todoId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["todoId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	if _, ok := members["workspaceId"]; !ok {
		return errors.New("required JSON field is missing")
	}
	if raw, ok := members["workspaceId"]; ok && bytes.Equal(bytes.TrimSpace(raw), []byte("null")) {
		return errors.New("non-nullable JSON field is null")
	}
	*value = ModelUpdateTodo(decoded)
	return nil
}

type ModelUpdateTodoCompleted bool

type ModelUpdateTodoRevision int64

type ModelUpdateTodoTitle string

type ModelUpdateTodoTodoId string

type ModelUpdateTodoWorkspaceId string

type OpTodosCreateHandler interface {
	HandleTodosCreate(context.Context, OpTodosCreateRequest) (OpTodosCreateResponse, error)
}

type OpTodosCreateRequest struct {
	Body ModelCreateTodo `json:"-"`
}

type OpTodosCreateResponse = ModelTodo

type OpTodosDeleteHandler interface {
	HandleTodosDelete(context.Context, OpTodosDeleteRequest) (OpTodosDeleteResponse, error)
}

type OpTodosDeleteRequest struct {
	Body ModelDeleteTodo `json:"-"`
}

type OpTodosDeleteResponse struct{}

type OpTodosListHandler interface {
	HandleTodosList(context.Context, OpTodosListRequest) (OpTodosListResponse, error)
}

type OpTodosListRequest struct {
	Body ModelListTodos `json:"-"`
}

type OpTodosListResponse = ModelTodoList

type OpTodosUpdateHandler interface {
	HandleTodosUpdate(context.Context, OpTodosUpdateRequest) (OpTodosUpdateResponse, error)
}

type OpTodosUpdateRequest struct {
	Body ModelUpdateTodo `json:"-"`
}

type OpTodosUpdateResponse = ModelTodo

var operationMetadata = [...]OperationMetadata{
	{Method: "POST", Path: "/todos", Policy: OperationPolicy{OperationID: "todos.create", Permissions: []string{"todos:write"}, Entitlements: []string{}, Assurance: "aal1", SideEffect: "write", Idempotency: "forbidden", MCP: "never"}},
	{Method: "DELETE", Path: "/todos/delete", Policy: OperationPolicy{OperationID: "todos.delete", Permissions: []string{"todos:write"}, Entitlements: []string{}, Assurance: "aal1", SideEffect: "write", Idempotency: "forbidden", MCP: "never"}},
	{Method: "POST", Path: "/todos/search", Policy: OperationPolicy{OperationID: "todos.list", Permissions: []string{"todos:read"}, Entitlements: []string{}, Assurance: "aal1", SideEffect: "read", Idempotency: "forbidden", MCP: "never"}},
	{Method: "PUT", Path: "/todos", Policy: OperationPolicy{OperationID: "todos.update", Permissions: []string{"todos:write"}, Entitlements: []string{}, Assurance: "aal1", SideEffect: "write", Idempotency: "forbidden", MCP: "never"}},
}

func RegisteredOperations() []OperationMetadata {
	result := make([]OperationMetadata, len(operationMetadata))
	copy(result, operationMetadata[:])
	for i := range result {
		result[i].Policy.Permissions = append([]string(nil), result[i].Policy.Permissions...)
		result[i].Policy.Entitlements = append([]string(nil), result[i].Policy.Entitlements...)
	}
	return result
}
