// Package gotypes emits typed Go API models and business handler interfaces
// from the validated AMOS OpenAPI contract.
package gotypes

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/ajent-social/amos/internal/codegen"
	"github.com/pb33f/libopenapi"
	"github.com/pb33f/libopenapi/datamodel"
)

const (
	GeneratedHeader  = "// Code generated by AMOS Go types generator v1; DO NOT EDIT.\n"
	GeneratedPackage = "apigen"
	MaxSchemaDepth   = 32
)

var componentNamePattern = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9._-]{0,119}$`)

type schemaIR struct {
	ref      string
	kind     string
	format   string
	nullable bool
	fields   []schemaField
	required map[string]bool
	item     *schemaIR
}

type schemaField struct {
	jsonName string
	goName   string
	schema   *schemaIR
}

type typeInfo struct {
	typeName string
	baseName string
	nullable bool
}

type handlerModel struct {
	operation codegen.Operation
}

type generator struct {
	types          map[string]string
	decls          map[string]string
	componentNames map[string]string
	componentIR    map[string]*schemaIR
	componentInfo  map[string]typeInfo
	emitting       map[string]bool
}

// Generate validates the complete contract before emitting Go source. The
// current transport model accepts closed objects, scalars and homogeneous
// arrays; unsupported JSON Schema shapes are explicit errors.
func Generate(source []byte) ([]byte, error) {
	manifest, err := codegen.Validate(source)
	if err != nil {
		return nil, err
	}
	document, err := libopenapi.NewDocumentWithConfiguration(source, &datamodel.DocumentConfiguration{
		AllowFileReferences: false, AllowRemoteReferences: false,
	})
	if err != nil {
		return nil, errors.New("OpenAPI parser rejected the validated contract")
	}
	model, err := document.BuildV3Model()
	if err != nil || model == nil || model.Model.Paths == nil {
		return nil, errors.New("unable to build typed models from OpenAPI contract")
	}
	gen := &generator{
		types: make(map[string]string), decls: make(map[string]string),
		componentNames: make(map[string]string), componentIR: make(map[string]*schemaIR),
		componentInfo: make(map[string]typeInfo), emitting: make(map[string]bool),
	}
	for _, reserved := range []string{"OptionalNullable", "ErrorResponse", "OperationPolicy", "OperationMetadata"} {
		if err := gen.reserve(reserved, "built-in API type"); err != nil {
			return nil, err
		}
	}

	if model.Model.Components != nil && model.Model.Components.Schemas != nil {
		for componentName, proxy := range model.Model.Components.Schemas.FromOldest() {
			if !componentNamePattern.MatchString(componentName) {
				return nil, fmt.Errorf("components.schemas[%q]: name cannot be represented as a Go identifier", componentName)
			}
			goName, err := goIdentifier("Model", componentName)
			if err != nil {
				return nil, fmt.Errorf("components.schemas[%q]: %w", componentName, err)
			}
			if err := gen.reserve(goName, "component schema"); err != nil {
				return nil, fmt.Errorf("components.schemas[%q]: %w", componentName, err)
			}
			gen.componentNames[componentName] = goName
			ir, err := parseSchema(proxy, "components.schemas["+componentName+"]", 0)
			if err != nil {
				return nil, err
			}
			gen.componentIR[componentName] = ir
		}
	}
	for componentName := range gen.componentIR {
		if _, err := gen.resolveComponent(componentName); err != nil {
			return nil, err
		}
	}
	for componentName := range gen.componentIR {
		if err := gen.emitComponent(componentName); err != nil {
			return nil, err
		}
	}

	models := make([]handlerModel, 0, len(manifest.Operations))
	for _, operation := range manifest.Operations {
		goOp, err := goIdentifier("Op", operation.Policy.OperationID)
		if err != nil {
			return nil, fmt.Errorf("operation %s: %w", operation.Policy.OperationID, err)
		}
		requestName, responseName := goOp+"Request", goOp+"Response"
		handlerName, err := goIdentifier("Handle", operation.Policy.OperationID)
		if err != nil {
			return nil, fmt.Errorf("operation %s: %w", operation.Policy.OperationID, err)
		}
		for _, declaration := range []string{requestName, goOp + "Handler"} {
			if err := gen.reserve(declaration, "operation scaffold"); err != nil {
				return nil, fmt.Errorf("operation %s: %w", operation.Policy.OperationID, err)
			}
		}
		pathItem := model.Model.Paths.PathItems.GetOrZero(operation.Path)
		if pathItem == nil {
			return nil, fmt.Errorf("operation %s: parsed path is missing", operation.Policy.OperationID)
		}
		if len(pathItem.Parameters) != 0 {
			return nil, fmt.Errorf("operation %s: path-level parameters are unsupported by Go type generator v1", operation.Policy.OperationID)
		}
		openAPIOperation := pathItem.GetOperations().GetOrZero(strings.ToLower(operation.Method))
		if openAPIOperation == nil {
			return nil, fmt.Errorf("operation %s: parsed operation is missing", operation.Policy.OperationID)
		}
		if len(openAPIOperation.Parameters) != 0 {
			return nil, fmt.Errorf("operation %s: operation parameters are unsupported by Go type generator v1", operation.Policy.OperationID)
		}
		generatedModel := handlerModel{operation: operation}
		if openAPIOperation.RequestBody != nil {
			bodyRequired := openAPIOperation.RequestBody.Required != nil && *openAPIOperation.RequestBody.Required
			payload, _, err := onlyJSONMedia(openAPIOperation.RequestBody.Content, "requestBody", operation.Policy.OperationID)
			if err != nil {
				return nil, err
			}
			ir, err := parseSchema(payload.Schema, "operation "+operation.Policy.OperationID+" requestBody schema", 0)
			if err != nil {
				return nil, err
			}
			bodyInfo, err := gen.ensureType(ir, goOp+"RequestBody", 0)
			if err != nil {
				return nil, err
			}
			bodyFieldType := bodyInfo.typeName
			if bodyInfo.nullable {
				if bodyRequired {
					bodyFieldType = "*" + bodyInfo.baseName
				} else {
					bodyFieldType = "OptionalNullable[" + bodyInfo.baseName + "]"
				}
			} else if !bodyRequired {
				bodyFieldType = "*" + bodyInfo.typeName
			}
			if err := gen.define(requestName, "operation scaffold", "type "+requestName+" struct { Body "+bodyFieldType+" `json:\"-\"` }\n"); err != nil {
				return nil, err
			}
		} else {
			if err := gen.define(requestName, "operation scaffold", "type "+requestName+" struct{}\n"); err != nil {
				return nil, err
			}
		}

		response, status, err := successResponse(openAPIOperation, operation.Policy.OperationID)
		if err != nil {
			return nil, err
		}
		_ = status
		if response == nil || response.Content == nil {
			if err := gen.define(responseName, "operation scaffold", "type "+responseName+" struct{}\n"); err != nil {
				return nil, err
			}
		} else {
			payload, _, err := onlyJSONMedia(response.Content, "success response", operation.Policy.OperationID)
			if err != nil {
				return nil, err
			}
			ir, err := parseSchema(payload.Schema, "operation "+operation.Policy.OperationID+" response schema", 0)
			if err != nil {
				return nil, err
			}
			responseInfo, err := gen.ensureType(ir, responseName, 0)
			if err != nil {
				return nil, err
			}
			if ir.ref != "" {
				if err := gen.define(responseName, "operation scaffold", "type "+responseName+" = "+gen.componentNames[ir.ref]+"\n"); err != nil {
					return nil, err
				}
			} else if responseInfo.typeName != responseName {
				if err := gen.define(responseName, "operation scaffold", "type "+responseName+" = "+responseInfo.typeName+"\n"); err != nil {
					return nil, err
				}
			}
		}
		gen.types[goOp+"Handler"] = fmt.Sprintf("type %s interface {\n%s(context.Context, %s) (%s, error)\n}\n", goOp+"Handler", handlerName, requestName, responseName)
		models = append(models, generatedModel)
	}

	return gen.render(models)
}

func (g *generator) render(models []handlerModel) ([]byte, error) {
	var source bytes.Buffer
	source.WriteString(GeneratedHeader)
	source.WriteString("package " + GeneratedPackage + "\n\n")
	source.WriteString("import (\n\t\"bytes\"\n\t\"context\"\n\t\"encoding/json\"\n\t\"errors\"\n\t\"io\"\n)\n\n")
	source.WriteString(optionalHelpers)
	source.WriteString("type ErrorResponse struct {\n\tCode string `json:\"code\"`\n\tMessage string `json:\"message\"`\n\tRequestID string `json:\"requestId\"`\n}\n\n")
	source.WriteString(`type OperationPolicy struct {
 OperationID string
 Permissions []string
 Entitlements []string
 Assurance string
 SideEffect string
 Idempotency string
 MCP string
}
type OperationMetadata struct { Method string; Path string; Policy OperationPolicy }
`)

	typeNames := make([]string, 0, len(g.types))
	for name := range g.types {
		typeNames = append(typeNames, name)
	}
	sort.Strings(typeNames)
	for _, name := range typeNames {
		source.WriteString(g.types[name])
		source.WriteByte('\n')
	}

	source.WriteString("var operationMetadata = [...]OperationMetadata{\n")
	for _, model := range models {
		policy := model.operation.Policy
		source.WriteString("{Method: " + strconv.Quote(model.operation.Method) + ", Path: " + strconv.Quote(model.operation.Path) + ", Policy: OperationPolicy{")
		source.WriteString("OperationID: " + strconv.Quote(policy.OperationID) + ", Permissions: " + stringSliceLiteral(policy.Permissions) + ", Entitlements: " + stringSliceLiteral(policy.Entitlements) + ", Assurance: " + strconv.Quote(policy.Assurance) + ", SideEffect: " + strconv.Quote(policy.SideEffect) + ", Idempotency: " + strconv.Quote(policy.Idempotency) + ", MCP: " + strconv.Quote(policy.MCP) + "}},\n")
	}
	source.WriteString("}\n\nfunc RegisteredOperations() []OperationMetadata {\nresult := make([]OperationMetadata, len(operationMetadata))\ncopy(result, operationMetadata[:])\nfor i := range result { result[i].Policy.Permissions = append([]string(nil), result[i].Policy.Permissions...); result[i].Policy.Entitlements = append([]string(nil), result[i].Policy.Entitlements...) }\nreturn result\n}\n")

	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return nil, errors.New("generated Go source did not format")
	}
	return formatted, nil
}

func stringSliceLiteral(values []string) string {
	quoted := make([]string, len(values))
	for i, value := range values {
		quoted[i] = strconv.Quote(value)
	}
	return "[]string{" + strings.Join(quoted, ",") + "}"
}

func goIdentifier(prefix, source string) (string, error) {
	if source == "" {
		return "", errors.New("generated identifier is empty")
	}
	var builder strings.Builder
	if prefix != "" {
		builder.WriteString(prefix)
	}
	capitalize := true
	for _, r := range source {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			if capitalize {
				if r >= 'a' && r <= 'z' {
					r -= 'a' - 'A'
				}
				capitalize = false
			}
			builder.WriteRune(r)
		} else {
			capitalize = true
		}
	}
	name := builder.String()
	if name == "" || !token.IsIdentifier(name) || token.Lookup(name).IsKeyword() {
		return "", errors.New("name cannot be represented as a safe Go identifier")
	}
	return name, nil
}

func (g *generator) reserve(name, source string) error {
	if !token.IsIdentifier(name) || token.Lookup(name).IsKeyword() {
		return errors.New("generated name is not a valid Go identifier")
	}
	if prior, exists := g.decls[name]; exists {
		return fmt.Errorf("generated Go name collision between %s and %s", prior, source)
	}
	g.decls[name] = source
	return nil
}

var optionalHelpers = `type OptionalNullable[T any] struct { Value T; Present bool; Null bool }
func (field *OptionalNullable[T]) UnmarshalJSON(data []byte) error {
 field.Present = true
 if bytes.Equal(bytes.TrimSpace(data), []byte("null")) { field.Null = true; var zero T; field.Value = zero; return nil }
 field.Null = false
 return json.Unmarshal(data, &field.Value)
}
func (field OptionalNullable[T]) MarshalJSON() ([]byte, error) {
 if field.Null { return []byte("null"), nil }
 return json.Marshal(field.Value)
}
type jsonMember struct { name string; value []byte }
func marshalObject(members []jsonMember) ([]byte, error) {
 var output bytes.Buffer
 output.WriteByte('{')
 for i, member := range members {
  if i > 0 { output.WriteByte(',') }
  name, err := json.Marshal(member.name); if err != nil { return nil, err }
  output.Write(name); output.WriteByte(':'); output.Write(member.value)
 }
 output.WriteByte('}')
 return output.Bytes(), nil
}
`

// Keep imported libopenapi types visible in this file's source signatures.
