-- Identity persistence proposal. The integration task assigns global order.
-- Every ID is generated by trusted application code with UUIDv7 and checked
-- here so a caller cannot persist a random or caller-selected ID silently.
CREATE TABLE identity_persons (
    id UUID PRIMARY KEY,
    installation_id UUID NOT NULL,
    application_id UUID NOT NULL,
    state TEXT NOT NULL CHECK (state IN (
        'pending_verification', 'active', 'self_disabled',
        'administratively_disabled', 'deletion_pending'
    )),
    security_epoch BIGINT NOT NULL DEFAULT 0 CHECK (security_epoch >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT identity_persons_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_persons_scope_key UNIQUE (id, installation_id, application_id)
);

CREATE TABLE identity_emails (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL,
    installation_id UUID NOT NULL,
    application_id UUID NOT NULL,
    display_address TEXT NOT NULL,
    comparison_key TEXT COLLATE "C" NOT NULL,
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT identity_emails_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_emails_person_scope_fk
        FOREIGN KEY (person_id, installation_id, application_id)
        REFERENCES identity_persons (id, installation_id, application_id),
    CONSTRAINT identity_emails_scope_address_key
        UNIQUE (installation_id, application_id, comparison_key),
    CONSTRAINT identity_emails_person_address_key
        UNIQUE (person_id, comparison_key),
    CONSTRAINT identity_emails_id_person_key UNIQUE (id, person_id)
);

CREATE TABLE identity_credentials (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL REFERENCES identity_persons (id),
    method TEXT NOT NULL CHECK (method IN ('email_password')),
    verifier_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    revoked_at TIMESTAMPTZ,
    CONSTRAINT identity_credentials_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_credentials_person_method_key UNIQUE (person_id, method)
);

CREATE TABLE identity_external_bindings (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL REFERENCES identity_persons (id),
    provider_connection_id UUID NOT NULL,
    provider TEXT COLLATE "C" NOT NULL,
    issuer TEXT COLLATE "C" NOT NULL,
    subject TEXT COLLATE "C" NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT identity_external_bindings_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_external_bindings_subject_key
        UNIQUE (provider_connection_id, issuer, subject)
);

CREATE TABLE identity_sessions (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL REFERENCES identity_persons (id),
    installation_id UUID NOT NULL,
    application_id UUID NOT NULL,
    environment_id UUID NOT NULL,
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    security_epoch BIGINT NOT NULL CHECK (security_epoch >= 0),
    authentication_method TEXT NOT NULL CHECK (authentication_method IN (
        'email_password', 'email_magic_link', 'google', 'github', 'apple',
        'passkey', 'enterprise_oidc'
    )),
    authenticated_at TIMESTAMPTZ NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    idle_expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT identity_sessions_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_sessions_environment_uuid_v7 CHECK (
        substring(environment_id::text, 15, 1) = '7' AND
        substring(environment_id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_sessions_person_scope_fk
        FOREIGN KEY (person_id, installation_id, application_id)
        REFERENCES identity_persons (id, installation_id, application_id),
    CONSTRAINT identity_sessions_expiry CHECK (
        authenticated_at <= issued_at AND expires_at > issued_at AND
        idle_expires_at > issued_at AND idle_expires_at <= expires_at
    )
);

CREATE TABLE identity_challenges (
    id UUID PRIMARY KEY,
    person_id UUID NOT NULL REFERENCES identity_persons (id),
    email_id UUID NOT NULL,
    purpose TEXT NOT NULL CHECK (purpose IN (
        'email_verification', 'password_reset', 'email_magic_link', 'email_change'
    )),
    token_digest BYTEA NOT NULL UNIQUE CHECK (octet_length(token_digest) = 32),
    created_at TIMESTAMPTZ NOT NULL DEFAULT transaction_timestamp(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    CONSTRAINT identity_challenges_uuid_v7 CHECK (
        substring(id::text, 15, 1) = '7' AND
        substring(id::text, 20, 1) IN ('8', '9', 'a', 'b')
    ),
    CONSTRAINT identity_challenges_expiry CHECK (expires_at > created_at),
    CONSTRAINT identity_challenges_email_person_fk
        FOREIGN KEY (email_id, person_id) REFERENCES identity_emails (id, person_id)
);

CREATE INDEX identity_sessions_active_person_idx
    ON identity_sessions (person_id, idle_expires_at, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX identity_challenges_open_person_idx
    ON identity_challenges (person_id, purpose, expires_at)
    WHERE consumed_at IS NULL;
